export const categories = [
    {
      id: 1,
      name: 'Drinks',
      image: require('../(menudependencies)/menuimgs/coffeecup.png'),
  
    },
    {
      id: 2,
      name: 'Snacks',
  image: require('../(menudependencies)/menuimgs/burger.png'),
    },
    {
      id: 3,
      name: 'Desserts',
       image: require('../(menudependencies)/menuimgs/cake.png'),
      },
      {
      id: 4,
      name: 'Specials',
       image: require('../(menudependencies)/menuimgs/star.png'),
    },
  ];
  
  export const items = [
    { 
      id: "1",
      name: "Latte",
      image: require('../(menudependencies)/menuimgs/latte.jpeg'),
      desciption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore, animi fugiat magnam totam, corporis earum dolorum quae, libero vitae ipsam quibusdam et voluptate molestiae ea? Quas possimus consectetur delectus. E",
      rating: "4.2",
      ingredient:"Milk, sugar, coffee, cream",
      price: "30",
      type: 'Drinks',
      isVeg: true,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
    {
      id: "2",
      name: "Capuccino",
    image: require('../(menudependencies)/menuimgs/capuccino.jpg'),
      rating: "4.6",
      price: "50",
      type: 'Drinks',
      isVeg: true,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
    {
      id: "3",
      name: "Black Coffee",
     image: require('../(menudependencies)/menuimgs/blackcoffee.jpg'),
      rating: "4.0",
      price: "30",
      type: 'Drinks',
      isVeg: true,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
    {
      id: "4",
      name: "Iced Coffee",
    image: require('../(menudependencies)/menuimgs/icedcoffee.webp'),
      rating: "4.1",
      price: "40",
      type: 'Drinks',
      isVeg: true,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
    {
      id: "5",
      name: "Chocolate Milkshake",
    image: require('../(menudependencies)/menuimgs/chocolatemilkshake.jpg'),
      rating: "4.1",
      price: "50",
      type: 'Drinks',
      isVeg: true,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
   
  
    { 
      id: "6",
      name: "Croissant",
     image: require('../(menudependencies)/menuimgs/croissant.webp'),
      rating: "4.2",
      price: "50",
      type: 'Snacks',
      isVeg: false,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
    {
      id: "7",
      name: "Veg Sandwich",
    image: require('../(menudependencies)/menuimgs/vegsandwich.jpg'),
      rating: "4.6",
      price: "65",
      type: 'Snacks',
      isVeg: true,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
    {
      id: "8",
      name: "Cheese Sandwich",
     image: require('../(menudependencies)/menuimgs/cheesesandwich.jpeg'),
      rating: "4.0",
      price: "60",
      type: 'Snacks',
      isVeg: true,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
    {
      id: "9",
      name: "Chicken Sandwich",
    image: require('../(menudependencies)/menuimgs/chickenwrap.jpg'),
      rating: "4.3",
      price: "70",
      type: 'Snacks',
      isVeg: false,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
      {
      id: "10",
      name: " Chicken Burger",
    image: require('../(menudependencies)/menuimgs/burger1.jpg'),
      rating: "4.8",
      price: "90",
      type: 'Snacks',
        isVeg: false,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
    
      {
      id: "11",
      name: " Chocolate cake",
    image: require('../(menudependencies)/menuimgs/chocolatecake.jpg'),
      rating: "4.7",
      price: "70",
        type: 'Desserts',
        isVeg: true,
      extras: ['Extra Cheese', 'Extra Sauce', 'Bacon'],
    },
      {
      id: "12",
      name: " Strawberry cake",
    image: require('../(menudependencies)/menuimgs/strawberrycake.jpg'),
      rating: "4.9",
      price: "80",
        type: 'Desserts',
      isVeg: true,
    },
       {
      id: "13",
      name: "Chocolate Brownie",
    image: require('../(menudependencies)/menuimgs/brownie.jpg'),
      rating: "4.4",
      price: "40",
        type: 'Desserts',
      isVeg: false,
    },
      
      
    //       {
    //   id: "10",
    //   name: "Fish",
    // image: require('../(menudependencies)/menuimgs/latte.jpeg'),
    //   rating: "4.1",
    //   price: "5$",
    //   type : 'Specials',
    // },
  ];